# Generated by Django 4.2.18 on 2025-06-02 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(choices=[('P', 'Pitcher'), ('C', 'Catcher'), ('IF', 'Infielder'), ('OF', 'Outfielder'), ('DH', 'Designated Hitter')], max_length=3)),
                ('war', models.FloatField(default=0.0)),
                ('batting_avg', models.FloatField(blank=True, null=True)),
                ('era', models.FloatField(blank=True, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
            ],
        ),
    ]
