# Generated by Django 5.2 on 2025-06-04 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_playerwar_delete_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerwar',
            name='team',
        ),
        migrations.RemoveField(
            model_name='playerwar',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='playerwar',
            name='war',
        ),
        migrations.AddField(
            model_name='playerwar',
            name='batting_avg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerwar',
            name='era',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerwar',
            name='position',
            field=models.CharField(max_length=10),
        ),
    ]
