# Generated by Django 5.2 on 2025-06-04 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_remove_playerwar_team_remove_playerwar_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerwar',
            name='war',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
