# Generated by Django 5.2 on 2025-06-04 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_playerwar_war'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=20)),
                ('batting_avg', models.FloatField(blank=True, null=True)),
                ('era', models.FloatField(blank=True, null=True)),
                ('views', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
