# Generated by Django 5.2 on 2025-06-04 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_alter_team_draws_alter_team_losses_alter_team_wins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='win_rate',
        ),
        migrations.AddField(
            model_name='team',
            name='highlights',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='team',
            name='matchups',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='team',
            name='waa',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='team',
            name='draws',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='losses',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='wins',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='TeamStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batting_avg', models.FloatField(null=True)),
                ('homeruns', models.IntegerField(null=True)),
                ('hits', models.IntegerField(null=True)),
                ('stolen_bases', models.IntegerField(null=True)),
                ('ops', models.FloatField(null=True)),
                ('era', models.FloatField(null=True)),
                ('whip', models.FloatField(null=True)),
                ('strikeouts', models.IntegerField(null=True)),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
            ],
        ),
        migrations.CreateModel(
            name='TeamWAR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pitcher', models.FloatField()),
                ('hitter', models.FloatField()),
                ('bench', models.FloatField()),
                ('defense', models.FloatField()),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
            ],
        ),
        migrations.CreateModel(
            name='VersusRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opponent', models.CharField(max_length=50)),
                ('wins', models.IntegerField()),
                ('draws', models.IntegerField(default=0)),
                ('losses', models.IntegerField()),
                ('win_rate', models.FloatField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versus', to='teams.team')),
            ],
        ),
    ]
