# Generated by Django 4.2.18 on 2025-06-04 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_remove_team_win_rate_team_highlights_team_matchups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='runs_allowed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='runs_scored',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
