# Generated by Django 4.2.18 on 2025-06-04 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_team_runs_allowed_team_runs_scored_team_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='games',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
