# Generated by Django 4.2.18 on 2025-06-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_team_games_alter_team_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='games',
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
