# Generated by Django 5.2.1 on 2025-06-08 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_remove_team_games_alter_team_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='runs_allowed',
        ),
        migrations.RemoveField(
            model_name='team',
            name='runs_scored',
        ),
        migrations.RemoveField(
            model_name='team',
            name='views',
        ),
    ]
